
package edu.jft.prashant.services.endpoints;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UtilServiceEndpoint", targetNamespace = "http://endpoints.services.prashant.jft.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtilServiceEndpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://endpoints.services.prashant.jft.edu/", className = "edu.jft.prashant.services.endpoints.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://endpoints.services.prashant.jft.edu/", className = "edu.jft.prashant.services.endpoints.EchoResponse")
    public String echo(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
