
package edu.jft.prashant.wsendpoints;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SpitterService", targetNamespace = "http://wsendpoints.prashant.jft.edu/", wsdlLocation = "http://localhost:7777/services/SpitterService?wsdl")
public class SpitterService
    extends Service
{

    private final static URL SPITTERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SpitterService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = SpitterService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7777/services/SpitterService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7777/services/SpitterService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SPITTERSERVICE_WSDL_LOCATION = url;
    }

    public SpitterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpitterService() {
        super(SPITTERSERVICE_WSDL_LOCATION, new QName("http://wsendpoints.prashant.jft.edu/", "SpitterService"));
    }

    /**
     * 
     * @return
     *     returns SpitterServiceEndpoint
     */
    @WebEndpoint(name = "SpitterServiceEndpointPort")
    public SpitterServiceEndpoint getSpitterServiceEndpointPort() {
        return super.getPort(new QName("http://wsendpoints.prashant.jft.edu/", "SpitterServiceEndpointPort"), SpitterServiceEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpitterServiceEndpoint
     */
    @WebEndpoint(name = "SpitterServiceEndpointPort")
    public SpitterServiceEndpoint getSpitterServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsendpoints.prashant.jft.edu/", "SpitterServiceEndpointPort"), SpitterServiceEndpoint.class, features);
    }

}
