
package edu.jft.prashant.wsendpoints;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SpitterServiceEndpoint", targetNamespace = "http://wsendpoints.prashant.jft.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpitterServiceEndpoint {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsername", targetNamespace = "http://wsendpoints.prashant.jft.edu/", className = "edu.jft.prashant.wsendpoints.GetUsername")
    @ResponseWrapper(localName = "getUsernameResponse", targetNamespace = "http://wsendpoints.prashant.jft.edu/", className = "edu.jft.prashant.wsendpoints.GetUsernameResponse")
    public String getUsername();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echoUsername", targetNamespace = "http://wsendpoints.prashant.jft.edu/", className = "edu.jft.prashant.wsendpoints.EchoUsername")
    @ResponseWrapper(localName = "echoUsernameResponse", targetNamespace = "http://wsendpoints.prashant.jft.edu/", className = "edu.jft.prashant.wsendpoints.EchoUsernameResponse")
    public String echoUsername(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
